### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by kennethkoontz** [usebenchmark/benchmark-insights#9]

**Comment by kennethkoontz** [comment]
```
[2015-04-05 19:49:37,864: ERROR/MainProcess] Task app.tasks.create_insight[1e0bf518-3d95-45e1-9c25-62395e7ed2ea] raised unexpected: TypeError("unsupported operand type(s) for +: 'NoneType' and 'int'",)
Traceback (most recent call last):
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/kenneth/Projects/benchmark/api/app/__init__.py", line 47, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/kenneth/Projects/benchmark/api/app/tasks.py", line 98, in create_insight
    stats[provider] = provider_stat.stats
  File "/Users/kenneth/Projects/benchmark-insights/benchmarkinsights/insights.py", line 22, in stats
    stats[attr] = getattr(self, attr)
  File "/Users/kenneth/Projects/benchmark-insights/benchmarkinsights/insights.py", line 82, in rating
    return {'average': round(np.average(rating), 1)}
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/numpy/lib/function_base.py", line 514, in average
    avg = a.mean(axis)
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/numpy/core/_methods.py", line 66, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
